@echo off
echo Setting up Ollama models for first-time run...
echo Pulling base model phi4:latest...
ollama pull phi4:latest
echo Creating custom model phi4-json from Modelfile...
ollama create phi4-json -f Modelfile
echo Pulling vision model deepseek-ocr:3b...
ollama pull deepseek-ocr:3b
echo Starting Ollama server...
ollama serve